package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "logger_test",
    srcs = ["logger_test.cc"],
    deps = [
        "//log:logger",
    ]
)
